#pragma config(Sensor, in1,    potent,         sensorPotentiometer)
#pragma config(Motor,  port6,           armPitch,      tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool safetyLock = false;

int TARGET = 4000;
// Desired arm position //

int MAX_OUT = 90;
// Maximum motor value //

int MAXPOT = 4095;
int MINPOT = 500;

int potVal = 0;

int difErr = 0;

int curErr = 0;

int curSpeed = 0;

float joyCal = 0.01;
// Joystick value multiplied by this //

float Kp = 0.1;
// Proportional. Difference from current to target //

//float Ki = 0.0007;
// Integral. Accelerates if it takes longer //

float Kd = 0.05;
// Differential. Increases and decreases speed according to difference from current to target //

//int totErr = 0;
// Total difference from current to target //

int preErr = 0;
// Previous difference from current to target //

task toggleLock()
{
	if(vexRT[Btn7U])
	{
		safetyLock = true;
	}
	if(vexRT[Btn8U])
	{
		TARGET = 4000;
		wait1Msec(1000);
		stopMotor[armPitch];
		safetyLock = false;
	}
}

task PID()// Changes motor speed based on target //
{
	while(safetyLock)
	{
		potVal = SensorValue[potent];
		// Assigns the value of sensor "potent" to the variable potVal //

		curErr = potVal - TARGET;
		// Assigns the value of TARGET minus the value of "potent" to curErr //
		//if(abs(totErr)<MAXPOT)
		//{
		//	totErr += curErr;
		//}
		// Adds the current error to the total error //

		difErr = curErr - preErr;
		// Assigns the value of the current error minus the previous error to difErr //

		curSpeed = curErr * Kp + difErr * Kd;
		//+ totErr / Ki + difErr / Kd;
		// Assigns curErr / Kp + totErr / Ki + difErr / Kd to curSpeed //

		if(abs(curSpeed) > MAX_OUT)// Prevents curSpeed from going past the maximum //
		{
			curSpeed = (curSpeed / abs(curSpeed))* MAX_OUT;
		}
		motor[armPitch] = curSpeed;
		preErr = curErr;
		wait1Msec(40);
	}
}

task controlTarget()// Controls the value of TARGET //
{
	while(safetyLock)
	{
		while(abs(vexRT[Ch2]) > 20)// Threshold //
		{
			if(TARGET < MINPOT)// Minimum value of TARGET //
			{
				TARGET = MINPOT;
			}
			else if(TARGET > MAXPOT)// Maximum value of TARGET //
			{
				TARGET = MAXPOT;
			}
			else// Adds and subtracts the value of the joystick to TARGET 4 times every second //
			{
				TARGET += vexRT[Ch2] * joyCal;
				wait1Msec(25);
			}
		}
	}
}

task main()
{
	while(true)
	{
		startTask(toggleLock);
		startTask(PID);
		startTask(controlTarget);
	}
}
