#pragma config(Motor,  port2,           driveA,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           driveB,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task motorRotate()
{// Will move motor 360* clockwise with one button, and 360* counter-clockwise with another button //

	while(true)// Program will constantly check for these events //
	{

		if(vexRT[Btn5U])// If Btn5U is pressed, rotate motor "drive" 360 degrees clockwise //
		{

			forward(1, rotations, 100);

		}
		else// If Btn5U is NOT pressed, check for next event //
		{

			if(vexRT[Btn6U])// If Btn6U is pressed, rotate motor "drive" 360 degrees counter-clockwise //
			{

				backward(1, rotations, 100);

			}
			else// If none of these events are triggered, stop motor "drive" //
			{

				stopMotor(driveA);
				stopMotor(driveB);

			}

		}

	}

}

task main()
{

	while(true)
	{

		startTask(motorRotate);

	}

}
