#pragma config(Motor,  port2,           drive,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task motorRotate()
{// Will move motor 360* clockwise with one button, and 360* counter-clockwise with another button //

	while(true)// Program will constantly check for these events //
	{

		bool leftTrigger;
		bool rightTrigger;


		if(vexRT[Btn5U])// If Btn5U is pressed, set boolean variable "leftTrigger" to true //
		{

			leftTrigger = true;

		}
		else// If Btn5U is NOT pressed, set boolean variable "leftTrigger" to false //
		{

			leftTrigger = false;

		}

		if(vexRT[Btn6U])// If Btn6U is pressed, set boolean variable "rightTrigger" to true //
		{

			rightTrigger = true;

		}
		else// If Btn6U is NOT pressed, set boolean variable "rightTrigger" to false //
		{

			rightTrigger = false;

		}

		while (leftTrigger == true)// while the boolean variable "leftTrigger" is true, set motor "drive" speed to 127 //
		{

			motor[drive] = 127;

		}

		while (rightTrigger)// while the boolean variable "rightTrigger" is true, set motor "drive" speed to -127 //
		{

			motor[drive] = -127;

		}

		while((rightTrigger == false)&&(leftTrigger == false))// while both boolean variables are false, stop motor "drive" //
		{

			stopMotor(drive);

		}

		while((rightTrigger == true)&&(leftTrigger == true))// while both boolean variables are true, stop motor "drive" //
		{

			stopMotor(drive);

		}

	}

}

task main()
{

	while(true)// continuously run all tasks //
	{

		startTask(motorRotate);

	}

}
